defaults: &defaults

development:
  <<: *defaults
  sessions:
    default:
      hosts:
        - 127.0.0.1:27017
      database: mayitemai_dev

test:
  <<: *defaults
  sessions:
    default:
      hosts:
        - 127.0.0.1:27017
      database: mayitemai_test

# set these environment variables on your prod server
production:
  <<: *defaults
  sessions:
    default:
      hosts:
        - 127.0.0.1:27017
      database: mayitemai
      options:
        pool_size: 64
